version: '3'
services:
    laravel:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: sail-8.2/app
        ports:
            - '8081:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        #volumes:
        #    - '.:/var/www/html'
